<?php 

require __DIR__.'/../config/database.php';

$users = [
    ["aurelien.vilette@gmail.com", "M.", "Vilette", "Aurélien", "aurelienVilette", "06.01.02.03.04" , true, "Né en 1982 au Chesnay près de Paris, c’est à la suite d’un changement radical de mode de vie qu’Aurélien Villette se recentre sur sa passion des voyages et découvre la photographie en 2008. Depuis, il a foulé plus d'une trentaine de pays à la rencontre de sociétés et d'histoires qui ont façonné sa propre vision du monde. Au-delà d'un simple souci documentaire et de pérennisation, il s'intéresse à la description et à l'esthétisation de lieux en déshérence. Les jeux de lumières, les matières vieillissantes, les perspectives et structures architecturales sont mis en évidence et magnifiés. Le silence, omniprésent, paraît correspondre à un temps qui se serait tu et fait émaner de ces photographies une atmosphère énigmatique, questionnant le spectateur sur la vie passée des lieux. Après avoir obtenu les Félicitations du Jury lors du concours SFR Jeunes Talents en 2012 avec sa série « Structures et Déstructures », il devient photographe professionnel et construit ses projets autour de ce qu'il appelle « l’esprit des lieux ».", null, "https://www.instagram.com/aurelienvillette/?hl=fr", null, null],

    ["john.wright@gmail.com", "M.", "Wright", "John", "johnWright", "06.11.22.33.44", true, "John Wright est un talentueux photographe britannique qui s’est fait connaître grâce aux portraits qu’il a réalisés des plus grandes stars de rock modernes. Le groupe U2, Lady Gaga, Paul McCartney ou encore Michael Jackson font partie de son corpus d’images au même titre que ses innombrables collaborations avec des prestigieux magazines (Vanity Fair, GQ), des studios situés entre Londres, Paris et Shanghai ou bien, des marques de luxe (Louis Vuitton, Dior et Fendi). Son cliché de la chanteuse Lily Allen posant avec des panthères noires a contribué à sa renommée internationale lui permettant de remporter la couverture de magazine de l’année en 2009. Originaire de Glasgow en Écosse, John Wright vient d’un milieu ouvrier et, malgré son installation dans la flamboyante ville de Los Angeles pour exercer son métier de photographe, il n’oublie pas ses racines et affirme lui-même : « Ce que je fais ne me définit pas, de la même manière que là où j'ai grandi ne me définit pas non plus. »", null, null, null, null],

    ["pedro.jarqueKrebs@gmail.com", "M.", "Jarque Krebs", "Pedro", "pedroJarqueKrebs", "06.55.55.55.55", true, "Des beautés féroces isolées de tout contexte comme si elles avaient été capturées dans leur intimité la plus secrète, tel est le remarquable geste artistique de Pedro Jarque qui permet de redonner aux animaux une partie de leur dignité volée. Formé en philosophie à l’Université Paris Sorbonne, le photographe péruvien a remporté de nombreuses distinctions tout au long de sa prolifique carrière et principalement grâce à ses captivants portraits animaliers. Originaire de Lima, il voyage au cœur de la nature amazonienne dès ses dix ans et se spécialise dans la photographie de paysages à partir des années 1980. Sujets de fascination très présents dans son travail, les animaux sauvages qu’il photographie dans des réserves naturelles le gratifient de multiples récompenses en 2016, telles que le Sony World Photography Awards, le Prix de la Photo (PX3), le Moscow International Foto Awards (MIFA) ou encore l’International Photography Awards (IPA).", null, null, null, null], 

    ["damien.dufresne@gmail.com", "M.", "Dufresne", "Damien", "damienDufresne", "06.44.44.44.44", true, "Damien Dufresne est un photographe atypique : reconnu dans les domaines du maquillage et de la publicité, il trouve dans son parcours de photographe d’art la liberté d’oublier les codes et les contraintes de la mode. … « La photographie d’art me donne une vraie liberté, je peux laisser libre cours à mon imagination, je ne cherche pas à provoquer mais je ne m’interdis rien, je suis mon instinct, je fais des images qui ont un sens pour moi, des images qui me parlent …» … « Pour moi, dessiner, peindre ou photographier est un moyen d’expression, de raconter des histoires sans utiliser les mots, une forme de langage, une façon différente de communiquer » … « La technique n’est pas une fin mais un moyen qui doit servir la créativité… l’émotion est ce qui compte le plus pour moi » … Sa force: la créativité, sa spécificité: les textures et les couleurs, son moteur: la passion. Damien Dufresne a travaillé à Paris, à Séoul, à Milan, à New York, à Tokyo. Il vit maintenant à Shanghaï. Publications 2005 《Wake up》Les Editions Assouline 2013 《Skin》Les Editions Assouline 2018 《One》Self-publication, imprimerie Shanghai Artron Expositions personnelles: 2012 Espace Pierre Cardin, Paris, France 2014 “Peinture sur soi”, Edward Achour Paris, Paris, France 2016 “Weird”, Salon H St Germain des Près, Paris, France 2016 “Through your eyes\" Marie Dalgar 7th Crossover Art Project, Shanghai, Chine 2018 “Clandestins”, YellowKorner Galerie Francs Bourgeois, Paris, France", null, null, null, null],

    ["alfredo.sanchez@gmail.com", "M.", "Sanchez", "Alfredo", "alfredoSanchez", "06.33.33.33.33", true, "Alfredo Sanchez ne se prédestinait pas à la photographie. Né à Mexico en 1954, il étudie le droit et se construit une carrière dans le secteur privé. “Mon temps libre, je l’occupais à jouer au tennis, monter à cheval, sans oublier mon passe-temps favoris : la photographie” raconte-t-il. Bien plus tard, vers la fin des années 1990, il prend un virage professionnel radical. Il abandonne sa carrière pour se consacrer à sa passion, la photographie. Nous sommes au début de l’ère digitale aussi Alfredo Sanchez se lance alors dans une formation intensive et complète consacrée à la photographie numérique. Il participe aux ateliers de grands photographes - Luis Caballo, Cuitlahuac Correa (Mexico), Jorge Salgado (Madrid), Antonio Leanza (Londres) ou encore Flor Acosta (Mexico) - et assiste à des séminaires aux quatre coins du globe. Aujourd’hui exposé dans le monde entier et maintes fois récompensé par ses pairs, Alfredo Sanchez se consacre à son art pour nous offrir une vision extraordinaire du monde qui nous entoure. Envoûtants, ses portraits sont minutieusement pensés pour créer des moments de pure utopie. Tel un chorégraphe, il compose chacun de ses clichés comme une danse pleine de couleurs, de textures et de beauté. Son souhait ? Attirer l’attention sur les merveilles du monde, souligner l'extraordinaire qui réside dans chaque vie ordinaire.", null, null, null, null], 

    ["thibaud.poirier@gmail.com", "M.", "Poirier", "Thibaud", "thibaudPoirier", "06.22.22.22.22", true, "Enfant d’expatrié, Thibaud Poirier a connu vécu son enfance dans de nombreuses villes du monde. Mais entre Houston, Montréal, Buenos-Aires ou Tokyo, c’est cette dernière qui l’a le plus influencé : « J’y ai découvert l’architecture, notamment de Tadao Ando, et c’est devenu une passion » explique-t-il, « aujourd’hui c’est le thème principal de ma photographie mais également mon activité professionnelle ». En effet, Thibaud Poirier, ingénieur de formation, travaille en parallèle de sa carrière de photographe, comme consultant en architecture d’intérieur à Paris. Il débute la photo en 2013 alors qu’il a 26 ans, avec un simple iPhone et les premières applications de retouches photo. Un de ses projets majeurs rassemble des photos de bibliothèques et d’églises : « J’ai choisi les bibliothèques et les églises parce je voulais regarder à travers l'histoire et montrer comment un espace avec une fonction similaire pouvait être interprété de manière aussi différente géographiquement et à travers les siècles. » Influencé par Candida Hofer et Hiroshi Sugimoto, il propose des photos vides de toute présence humaine pour « brosser des portraits surréalistes et intemporels de ces monuments. »", null, null, null, null],

    ["gama.agency@gmail.com", "M.", "Agency", "Gamma", "gammaAgency", "06.11.11.11.11", true, "Agence de photographie fondée en 1966 par plusieurs photographes, dont Raymond Depardon qui fut longtemps son directeur, afin de mieux contrôler leurs images et leurs sujets. Dans les années 70, l'agence Gamma a incarné, au côté de Sipa et Sygma, l'excellence du photo-journalisme à la française. Des photographes reconnus ont ainsi couvert les guerres, les événements politiques et les mouvements sociaux mais aussi alimenté la presse people en photographiant de nombreuses personnalités politiques et artistiques. Aujourd’hui l’agence est rattachée à Gamma Rapho : 1ère source européenne de photographies avec 20 millions d’images issues d’agences de renommée internationale (Gamma, Rapho, Keystone, Explorer, Jacana, Hoa-qui, Top et Stills).", null, null, null, null]


];

$db->query('SET FOREIGN_KEY_CHECKS = 0');
$db->query('TRUNCATE user');
$db->query('SET FOREIGN_KEY_CHECKS = 1');

foreach ($users as $user ) {
    $query =  $db->prepare("INSERT INTO user (email, civilite, nom, prenom, pwd, telephone, isArtiste, presentation, facebook, instagram, pinterest, twitter)
                          VALUES (:email, :civilite, :nom, :prenom, :pwd, :telephone, :isArtiste, :presentation, :facebook, :instagram, :pinterest, :twitter)");
    $query->bindValue(":email", $user[0]);
    $query->bindValue(":civilite", $user[1]);
    $query->bindValue(":nom", $user[2]);
    $query->bindValue(":prenom", $user[3]);
    $query->bindValue(":pwd", password_hash($user[4], PASSWORD_DEFAULT));
    $query->bindValue(":telephone", $user[5]);
    $query->bindValue(":isArtiste", $user[6]);
    $query->bindValue(":presentation", $user[7]);
    $query->bindValue(":facebook", $user[8]);
    $query->bindValue(":instagram", $user[9]);
    $query->bindValue(":pinterest", $user[10]);
    $query->bindValue(":twitter", $user[11]);
    $query->execute();
    
}
?>