<?php 

require __DIR__.'/../config/database.php';

$oeuvres = [
    ["VERTICALITE VOLUTE II POLOGNE", "Que dit un lieu abandonné d’une époque ? D’une civilisation ? D’un moment ? Autant de questions que l’on se pose en contemplant les photos d’Aurélien Villette. Le photographe a une passion pour l’architecture qui influence, dit-il, « l’ensemble de notre vie » et dont la variété est pour lui « chaque jour un émerveillement ». Quel que soit le pays concerné (dans cette série : Liban, Japon, Pologne ou France), c’est ce qu’il appelle « l’esprit des lieux », qu’il cherche à capter et à partager à travers ses photos.", 84, "verticaliteVoluteIIPologne.jpeg", 1000, 2, 3, 1],
    ["HOTEL SEVENTIES JAPAN", "Que dit un lieu abandonné d’une époque ? D’une civilisation ? D’un moment ? Autant de questions que l’on se pose en contemplant les photos d’Aurélien Villette. Le photographe a une passion pour l’architecture qui influence, dit-il, « l’ensemble de notre vie » et dont la variété est pour lui « chaque jour un émerveillement ». Quel que soit le pays concerné (dans cette série : Liban, Japon, Pologne ou France), c’est ce qu’il appelle « l’esprit des lieux », qu’il cherche à capter et à partager à travers ses photos.", 84, "hotelSeventiesJapan.jpeg", 1000, 1, 3, 1],
    ["VERTICALITE VOLUTE - POLOGNE", "Depuis 2008, Aurélien Villette interroge le sens et la valeur patrimoniale de bâtiments abandonnés ou en ruine. Si ces-derniers représentent une ère de l’histoire de l’architecture, ils sont par ailleurs les témoins de l’histoire particulière d’un pays, d’une région ou d’une civilisation vouée à disparaître. Tirée de la série « Verticalité » que le photographe consacre aux lieux de passage, cette image devient un décor éternel, magnifié par la poussière, les fissures et les décorations vieillissantes.", 89, "verticalVolutePologne.jpeg", 1000, 2, 3, 1],
    ["EROSIONS VENITIENNES II", "Depuis 2008, Aurélien Villette interroge le sens et la valeur patrimoniale de bâtiments abandonnés ou en ruine. Si ces-derniers représentent une ère de l’histoire de l’architecture, ils sont par ailleurs les témoins de l’histoire particulière d’un pays, d’une région ou d’une civilisation vouée à disparaître. À travers la série « Érosions Vénitiennes », le photographe français capture la fragile beauté de Venise, une ville flottante spectaculaire menacée par la montée des eaux.", 89, "erorsionsVenitiennesII.jpeg", 1000, 2, 3, 1],
    ["TOPOPHILIA LA VILLA ROSE LIBAN", "Que dit un lieu abandonné d’une époque ? D’une civilisation ? D’un moment ? Autant de questions que l’on se pose en contemplant les photos d’Aurélien Villette. Le photographe a une passion pour l’architecture qui influence, dit-il, « l’ensemble de notre vie » et dont la variété est pour lui « chaque jour un émerveillement ». Quel que soit le pays concerné (dans cette série : Liban, Japon, Pologne ou France), c’est ce qu’il appelle « l’esprit des lieux », qu’il cherche à capter et à partager à travers ses photos.", 84, "topophiliaLaVillaRoseLiban.jpeg", 1000, 2, 3, 1], 
    ["AU-DELA", "Aurélien Villette s’inspire principalement de bâtiments en ruine. Ceux-ci renvoient à l’âge d’or d’un passé révolu et symbolisent pour la plupart l’histoire d’un pays, d’une région ou d’une civilisation vouée à disparaître. En cherchant l’esprit des lieux dans chaque architecture, ses pérégrinations l’amènent à s’intéresser aux pays marqués ou ayant été marqués par un régime totalitaire, ou bien à ceux en zone de conflit. Les ruines deviennent alors des espaces de contemplation et de méditation.", 89, "au-dela.jpeg", 1000, 2, 3, 1],
    ["LA BICYCLETTE Italie", "Aurélien Villette s’inspire principalement de bâtiments en ruine. Ceux-ci renvoient à l’âge d’or d’un passé révolu et symbolisent pour la plupart l’histoire d’un pays, d’une région ou d’une civilisation vouée à disparaître. En cherchant l’esprit des lieux dans chaque architecture, ses pérégrinations l’amènent à s’intéresser aux pays marqués ou ayant été marqués par un régime totalitaire, ou bien à ceux en zone de conflit. Les ruines deviennent alors des espaces de contemplation et de méditation.", 89, "laBicycletteItalie.jpeg", 1000, 2, 3, 1],
    ["Réminiscence - le buffet", "Au-delà d'un simple souci documentaire et de pérennisation, Aurélien Villette s'intéresse à la description et à l'esthétisation de lieux en déshérence. Les jeux de lumières, les matières vieillissantes, les perspectives et structures architecturales sont mis en évidence et magnifiés. Le silence, omniprésent, paraît correspondre à un temps qui se serait tu et fait émaner de ces photographies une atmosphère énigmatique, questionnant le spectateur sur la vie passée et l'esprit de ces lieux.", 89, "reminiscence-leBuffet.jpeg", 1000, 2, 3, 1],
    ["Cuba verticalite", "Au-delà d’un simple souci documentaire et de pérennisation, Aurélien Villette s’intéresse à la description et à l’esthétisation de lieux en déshérence. Les jeux de lumières, les matières vieillissantes, les perspectives et structures architecturales sont mis en évidence et magnifiés. Le silence, omniprésent, paraît correspondre à un temps qui se serait tu et fait émaner de ces photographies une atmosphère énigmatique, questionnant le spectateur sur la vie passée et l’esprit de ces lieux.", 89, "cubaVerticalite.jpeg", 1000, 2, 3, 1],
    ["RÉMINISCENCE, LIVRÉS À EUX MÊMES", "Au-delà d’un simple souci documentaire et de pérennisation, Aurélien Villette s’intéresse à la description et à l’esthétisation de lieux en déshérence. Les jeux de lumières, les matières vieillissantes, les perspectives et structures architecturales sont mis en évidence et magnifiés. Le silence, omniprésent, paraît correspondre à un temps qui se serait tu et fait émaner de ces photographies une atmosphère énigmatique, questionnant le spectateur sur la vie passée et l’esprit de ces lieux.", 89, "reminiscenceLivresAEuxMemes.jpeg", 1000, 2, 3, 1],
    ["Palazzo Sotto Voce", "Au-delà d’un simple souci documentaire et de pérennisation, Aurélien Villette s’intéresse à la description et à l’esthétisation de lieux en déshérence. Les jeux de lumières, les matières vieillissantes, les perspectives et structures architecturales sont mis en évidence et magnifiés. Le silence, omniprésent, paraît correspondre à un temps qui se serait tu et fait émaner de ces photographies une atmosphère énigmatique, questionnant le spectateur sur la vie passée et l’esprit de ces lieux.", 89, "palazzoSottoVoce.jpeg", 1000, 2, 3, 1]




];

$db->query('SET FOREIGN_KEY_CHECKS = 0');
$db->query('TRUNCATE oeuvre');
$db->query('SET FOREIGN_KEY_CHECKS = 1');

foreach ($cadres as $cadre ) {
    $db->query("INSERT INTO cadre (nom, description, prix, image, quantite, orientation_id, categorie_id, user_id) VALUES ('$cadre[0]', '$cadre[1]', '$cadre[2]' )");
}